### ISSUE TITLE
Add deleteOptions to Managedcluster

### ISSUE THREAD

**Issue by ArenaSu** [open-cluster-management-io/ocm#25]
I suggest to add DeleteOption in Managedcluster for implementing following functions:

1. Set ClearPolicy in DeleteOption, then manifestworks and addons, etc  of the managedcluster will be deleted by force when exec kubectl delete managedcluster.
2. Set RetentionPolicy in DeleteOption, then manifestworks and addons, etc  of the managedcluster will be retained when exec kubectl delete managedcluster.

The demand was encountered in production environment.

Please Consider whether it is reasonable, thanks.

**Comment by qiujian16** [comment]
Thanks, I think the first scenario makes sense.
Not quite sure about the second scenario. We remove rbac for registration agent today after cluster is deleted. Which means the addon will all become unknown status even though they are not deleted. 

I think when managedcluster is deleting, we should delete all addons in the same ns at least, thought? @skeeey

**Comment by ArenaSu** [comment]
> Thanks, I think the first scenario makes sense. Not quite sure about the second scenario. We remove rbac for registration agent today after cluster is deleted. Which means the addon will all become unknown status even though they are not deleted.
> 
> I think when managedcluster is deleting, we should delete all addons in the same ns at least, thought? @skeeey

Addons should be deleted no matter whatever the DeleteOption is configured according to your analysis.

**Comment by skeeey** [comment]
for the second case, if we keep the addons, it may be useful to restore the addons?

@ArenaSu currently when we delete a managed cluster, we did not delete its  manifestworks/addons, this because in some cases, e.g. the manifestworks/addons may have deployment order or dependent, so we let manifestworks/addons creator do the delete action, and as you suggestion, if we have a clear policy, it will be make sense.

**Comment by ArenaSu** [comment]
> for the second case, if we keep the addons, it may be useful to restore the addons?

It's right.And it may be difficult to restore addons such as cluster-gateway with proxy using k-connectivity. There are high requirements for addons.

**Comment by ArenaSu** [comment]
We can define specifications such as fields or policy types to perform addons recovering.

**Comment by qiujian16** [comment]
@skeeey @ArenaSu I think the addon will not work anyway when we delete managedcluster since the registration has no permission to rotate certificate for itself or addons after cluster is deleted. We could add finalizer to the rolebinding for registration such that when cluster is deleted, the registration can still work until all addons are cleaned. But the deletion process is not reversible. 

I would want to clarify the process that we desire during the cluster deletion

today's process:

1. the user deletes the managedcluster resources.
2. controller remove registration/work agents' clusterrole/clusterrolebinding/rolebinding
3. work agent's rolebinding is pending in deletion if there is existing manifestwork
4. managedcluster resources is removed.

There are some cases that impacts this clean process
- the addon is not cleaned and will not work since registration do not rotate cert for it anymore
- if the user delete klusterlet on managed cluster at first, then delete managedcluster, the manifestwork will not be cleaned and also the work agent's rolebinding will be always in deleting state. The user in this case has to manually delete manifestwork and remove finalizers on the manifestwork.

option 2:
1. the user deletes the managedcluster resources.
2.  controller removes cluster ns and agents's clusterrole/clusterrolebinding
3. managedcluster resources is removed

- same as today's design, if the user delete klusterlet on managed cluster at first, then delete managedcluster, the manifestwork will not be cleaned, and the ns will be in deleting state. User cannot create a cluster with the same until ns is cleaned
- It is hard to control If there is dependencies in manifestwork or addons, for example, I want to run a manifestwork to do some clean job when the cluster is deleted

option 3:
1. the user deletes the managedcluster resources.
2. controller does nothing
3. managedcluster resources is removed

- there might security issue since registration/work agent's permission is out of control
- registration agent will create a cluster again.

option 3 might be a viable approach, since when registration recreates the managedcluster, the hubAcceptClient field will be reverted to false which wiped out the agents' permissions. And it might be more like what kubelet did today.

Other options?
