### ISSUE TITLE
Does this project support k3s?

### ISSUE THREAD

**Issue by onedayherocoming** [open-cluster-management-io/OCM#6]

**Comment by mikeshng** [comment]
We might need to revisit this support in the later version of `k3d`. Overall, it still works fine but there are some issues.
A IP address can be given now during the `k3d cluster create` command by passing a param so that makes it a bit easier during the join process.

The main issue seems to be the `k3d` now hide away the kube-public cluster-info configmap. The `clusteradm init` command is now capable of creating that configmap to bypass that problem but I don't think it's created properly (or maybe the role and rolebinding) is setup properly.  

The `clusteradm join` command also gives out an error about the spoke cluster not having that cluster-info configmap which is kind of confusing. It probably should be an error because the registration process is still successful afterwards.

**Comment by qiujian16** [comment]
a document for k3s has been provided in the webpages.

/close
